name: Test and release

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v3

      - id: setup-node
        name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - id: install-deps
        name: Install dependencies
        run: yarn install --frozen-lockfile

      - id: lint
        name: Lint code
        run: yarn run eslint ./src/ --ext .ts --debug

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node-version: ['16', '18']
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v3

      - id: setup-node
        name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - id: install-deps
        name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - id: build-pkg
        name: Build package
        run: yarn build

      - id: tests
        name: Run tests
        run: yarn test

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    # Restricts release to:
    #   1) pushes of release tags
    #   2) the default branch
    #   3) the base repository
    if: |
      github.event_name == 'push' && startsWith(github.ref, 'refs/tags') &&
      endsWith(github.event.base_ref, github.event.repository.default_branch) &&
      github.repository == 'reuters-graphics/teams-klaxon'
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}
      
      - id: config-git
        name: Configure git
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - id: setup-node
        name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
          scope: '@reuters-graphics'

      - id: install-deps
        name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - id: build-pkg
        name: Build package
        run: yarn build
      
      - id: build-docs
        name: Build docs
        run: |
          yarn build:docs
          git commit --allow-empty -am "${{ github.ref_name }} docs"

      - id: version
        name: Version
        run: npm version ${{ github.ref_name }} --no-git-tag-version

      - id: publish
        name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - id: commit
        name: Commit
        run: |
          git commit -am "published ${{ github.ref_name }}"
          git push